fix: ci/cd

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -39,6 +39,12 @@ jobs:
       - name: Build application
         run: pnpm build
 
+      - name: Debug build output
+        run: |
+          pwd
+          ls -la
+          ls -la dist || echo "❌ dist not found"
+
       # 7️⃣ Upload build artifacts to EC2
       - name: Upload build to EC2
         uses: appleboy/scp-action@v0.1.7
